### ISSUE TITLE
Оплата провайдера через qiwi

### ISSUE THREAD

**Issue by mousesport** [dukei/any-balance-providers#1001]
Если уже созданный провайдер имеет возможность принимать оплату через киви
например ab-internet-stupinoSU
https://qiwi.com/payment/form/27335
как прикручивается возможность пополнения из программы?

**Comment by mousesport** [comment]
Дим дай коммент

**Comment by dukei** [comment]
Есть такой файл https://anybalance.ru/topup.json
Вот там это прописывается. Можете составить блок для нужного провайдера по аналогии с остальными, я добавлю в этот файл.

**Comment by mousesport** [comment]
Дим версион повысил до 7, 
проверь в ab-money-strelka надеюсь все правильно, т.к непонятно будет ли работать, если карта в настройках имеет значение "автоматически" (поиск происходит в ЛК), а в результс номера ее нет. 
https://pastebin.com/zWzMNRuk

**Comment by mousesport** [comment]
@dukei Дим добавь...

**Comment by mousesport** [comment]
Дим обновишь?

**Comment by dukei** [comment]
Обновил. Проверь, пожалуйста, что появились кнопки Пополнения в программе.

**Comment by mousesport** [comment]
Дим, а почему параметр сумма не передается ни в одном аккаунте ?15:53, 2 июля 2018 г., Dmitry Kochin <notifications@github.com>:Обновил. Проверь, пожалуйста, что появились кнопки Пополнения в программе.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

отправлено с мобильной почты
