### ISSUE TITLE
Не работает Крц Прикамье

### ISSUE THREAD

**Issue by AlekseyShi** [dukei/any-balance-providers#1005]
Выдаёт изменился сайт?

**Comment by dukei** [comment]
Добрый день!

Пришлите, пожалуйста, последний лог, обязательно с комментарием, что не
работает. Долгое нажатие на аккаунте и
выберите Показать последний лог. Затем меню Послать автору (или значок
Поделиться) и пошлите,
пожалуйста, по емейл.



2018-04-10 2:44 GMT+03:00 balda <notifications@github.com>:

**Comment by baldabalda** [comment]
Ушло

**Comment by AlekseyShi** [comment]
https?

**Comment by AlekseyShi** [comment]
Исправлено.
