### ISSUE TITLE
Неск. мес. не работает Bloomberg Gold

### ISSUE THREAD

**Issue by ex007ps** [dukei/any-balance-providers#1066]
Значения пусты

**Comment by dukei** [comment]
Добрый день!

Пришлите, пожалуйста, последний лог, обязательно с комментарием, что не
работает. Долгое нажатие на аккаунте и
выберите Показать последний лог. Затем меню Послать автору (или значок
Поделиться) и пошлите,
пожалуйста, по емейл.


чт, 4 апр. 2019 г. в 11:43, ex007ps <notifications@github.com>:

**Comment by ex007ps** [comment]
Добрый! Лог ушёл на AnyBalance Team • info@anybalance.ru

Не показывает ничего по золоту.

вт, 16 апр. 2019 г., 12:42 Dmitry Kochin <notifications@github.com>:
