### ISSUE TITLE
Провайдеры из ab-internet-mts не работают

### ISSUE THREAD

**Issue by dbrozen** [dukei/any-balance-providers#1075]
У всех провайдеров из ab-internet-mts на страницах вида "api.php?r=site/login" добавилась капча и они перестали работать.
...
Введите символы с картинки:
...
<img src="data:image/png;base64,
...

**Comment by dukei** [comment]
Так всё ж правильно, в этом случае провайдер просто показывает капчу. Разве нет?

**Comment by dbrozen** [comment]
Нет, провайдер ничего не знает о капче и не показывает ее и отправляет
форму без
LoginForm[captcha].  И, естественно, получает ошибку "Символы с картинки
введены неправильно"

Надо добавлять поддржку капчи по примеру
commit 5ada4593352d225df0a12e5cb18a717607e4e332
Author: Dmitry Kochin <dco@mail.ru>
Date:   Sun Mar 10 16:51:31 2019 +0300

    МТС (Россия) (ab-cell-mts-russia):
    Исправлен вход в случае капчи

**Comment by dukei** [comment]
Да, действительно, я понял, что вы имеете в виду. Исправление уже в каталоге:
http://anybalance.ru/catalog/ab-internet-mts/?inapp=no

**Comment by dbrozen** [comment]
Спасибо, потестил - работает.
