### ISSUE TITLE
Слетела лицензия на устройство

### ISSUE THREAD

**Issue by dbrozen** [dukei/any-balance-providers#1130]
Просьба восстановить
![Screenshot_20200731_075057_com dukei android apps anybalance](https://user-images.githubusercontent.com/2663372/89001399-cb27cd00-d302-11ea-8be4-cd67dfe5053a.jpg)
![Screenshot_20200731_075039_com google android gm](https://user-images.githubusercontent.com/2663372/89001402-cc58fa00-d302-11ea-8137-29706b7b8407.jpg)

**Comment by dbrozen** [comment]
А интересно, сколько времени занимает восстановление купленой лицензии?

**Comment by dukei** [comment]
Лицензия восстановлена. Спасибо вам большое за поддержку!

пт, 7 авг. 2020 г. в 14:16, dbrozen <notifications@github.com>:
