### ISSUE TITLE
Manifest

### ISSUE THREAD

**Issue by mousesport** [dukei/any-balance-providers#1180]
что за флаги и на что они влияют? какие значения могут принимать?
```
<api flags="no_browser"/>
<api min_level="5"/>
```

в вики
https://github.com/dukei/any-balance-providers/wiki/Manifest
не задокументировано

**Comment by DimaZUA** [comment]
min_level - версия API (версия самой программы). В коде возвращается через AnyBalance.getLevel() . Возвращает именно версию установленного API, а не указаннаю в манифесте.  Например, для работы SaveData(), saveCookies(), restoreCookies() нужен AnyBalance.getLevel()>=9,  а для retrieveCode() нужен AnyBalance.getLevel()>=7
[Примеры исползования](https://github.com/dukei/any-balance-providers/search?q=getLevel%28%29)
