### ISSUE TITLE
Слетела лицензия

### ISSUE THREAD

**Issue by shcoder** [dukei/any-balance-providers#1199]
В конце августа 2019 покупал лицензию пожизненно на устройство. Месяц назад лицензия слетела.
![image](https://user-images.githubusercontent.com/831141/125835582-ac80e0f6-5155-4ab9-9595-bdc023b59bb6.png)
![image](https://user-images.githubusercontent.com/831141/125835655-44dd6ab8-c5b3-4663-b92e-3d862b151d65.png)

**Comment by RdeWilde** [comment]
Dukei is a known scammer from Ties.db. They stole many thousands of dollars from many people. Do not trust him or his code with any of your assets

**Comment by shcoder** [comment]
Автор, я понимаю что ты забил на проект. Но нельзя же так наплевательски относится к тем, кто денежки тебе заплатил. Шарик то он круглый, а бумеранг он бумеранг

**Comment by dukei** [comment]
Зачем эти резкости? В чем у вас вопрос?

вт, 28 сент. 2021 г. в 16:03, ShCoder ***@***.***>:
