### ISSUE TITLE
Провайдер: BTC-e PAMM Счет провайдера и подписчика

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dukei/any-balance-providers#219]
```
Получает состояние PAMM-счета подписчика для 
одного провайдера и самого провайдера 
биржи BTC-e.
Обязательное поле - имя провайдера счета, 
для отслеживания изменений счета 
подписчика следует ввести логин-пароль от 
сайта https://pamm.btc-e.com, при желании - начальную 
сумму вклада и процент ставки провайдера.
```

Original issue reported on code.google.com by `sniper.m...@gmail.com` on 28 Jan 2015 at 11:56

Attachments:
- [ab-pamm-btce.zip](https://storage.googleapis.com/google-code-attachments/any-balance-providers/issue-219/comment-0/ab-pamm-btce.zip)

**Comment by mousesport** [comment]
Неактуально, т.к btc-е заменили на wex, а памов у них нет.
