### ISSUE TITLE
Patch for /trunk/ab-internet-wbt/main.js

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dukei/any-balance-providers#263]
```
изменена ссылка
```

Original issue reported on code.google.com by `aleksey....@gmail.com` on 23 May 2015 at 4:31

Attachments:
- [main.js.patch](https://storage.googleapis.com/google-code-attachments/any-balance-providers/issue-263/comment-0/main.js.patch)

**Comment by mousesport** [comment]
неактуально
