### ISSUE TITLE
провайдер биржи ссылок Sape

### ISSUE THREAD

**Issue by Serg1000** [dukei/any-balance-providers#273]
Ошибка при обновлении "изменился адрес сайта"

**Comment by dukei** [comment]
Добрый день!

Пришлите, пожалуйста, последний лог, обязательно с комментарием, что не
работает. Долгое нажатие на аккаунте и
выберите Показать последний лог. Затем меню Послать автору (или значок
Поделиться) и пошлите,
пожалуйста, по емейл.



2015-08-18 3:40 GMT+03:00 Serg1000 <notifications@github.com>:

**Comment by mousesport** [comment]
проверил провайдер работает.
