### ISSUE TITLE
YouSystem provider ( ab-bonus-dyakuyou ) not working

### ISSUE THREAD

**Issue by sniper-developer** [dukei/any-balance-providers#279]
Exception in onResult: Counter
Место последней транзакции is specified as numeric, but contains unparsable value: 41-XXX Киiв, вул. ХХХ, 15

**Comment by dukei** [comment]
Спасибо, исправлено: http://anybalance.ru/catalog.php?id=ab-bonus-dyakuyou&inapp=no
