### ISSUE TITLE
Обновить провайдер MobileTeleCom

### ISSUE THREAD

**Issue by etamin419** [dukei/any-balance-providers#297]
У провайдера обновился сайт, обновил все ссылке и нужно скинуть теперь в общий каталог

Смотрю и тут сайт обновился, как закинуть в общий каталог?

**Comment by dukei** [comment]
Можно клонировать репозиторий и сделать pull request, например

18 ноября 2015 г., 13:35 пользователь etamin419 <notifications@github.com>
написал:

**Comment by etamin419** [comment]
клонировал репозиторий, пытаюсь сделать pull request, но кнопки нет чтобы опубликовать.
PS тяжело изучать без мануала)

**Comment by dukei** [comment]
Вот, например, статья о пулреквестах: http://habrahabr.ru/post/125999/

18 ноября 2015 г., 14:56 пользователь etamin419 <notifications@github.com>
написал:

**Comment by etamin419** [comment]
Спасибо за ссылку, разобрался.

**Comment by etamin419** [comment]
каковы мои дальнейшие действия, чтобы файлы обновились в каталоге провайдера AllBalance ?

**Comment by dukei** [comment]
А где ваш пулреквест? Что-то я его не вижу.
Вот все пулреквесты, ни одного за вашим авторством: https://github.com/dukei/any-balance-providers/pulls

**Comment by etamin419** [comment]
Он лежит тут https://github.com/etamin419/ab-internet-StelsCom_MobileTeleCom/pulls
сейчас поищу тогда как к вам закинуть в директорию

**Comment by etamin419** [comment]
сделал пулреквест, лежит тут
https://github.com/dukei/any-balance-providers/pull/320

**Comment by etamin419** [comment]
можно еще убрать лишнего провайдера, а то получился дубликат с неправильным названием (неправильно тогда назвал)
http://anybalance.ru/catalog.php?id=ab-internet-StelsCom_MobileTeleCom&key=
