### ISSUE TITLE
интересный сервис для гитхаба

### ISSUE THREAD

**Issue by mousesport** [dukei/any-balance-providers#306]
Есть free сервис
https://ifttt.com/recipes/323153-create-a-new-github-issue-via-email
может при отправке мыла c заданными #хештегами или словами
на trigger@recipe.ifttt.com c вашего адреса привязанного на гихабе
может создавать новые Issues

можно прикрутить....
при отправке последнего лога автору сразу же будет открытая заявка в репозитории

**Comment by dukei** [comment]
спасибо, но пока у нас нет в этом необходимости.
