### ISSUE TITLE
Изменения OTTCLUB

### ISSUE THREAD

**Issue by TheGoblinHero** [dukei/any-balance-providers#311]
Сайт биллинга переехал на ottclub.cc, надо подправить провайдера.

**Comment by dukei** [comment]
Добрый день!

Пришлите, пожалуйста, последний лог, обязательно с комментарием, что не
работает. Долгое нажатие на аккаунте и
выберите Показать последний лог. Затем меню Послать автору (или значок
Поделиться) и пошлите,
пожалуйста, по емейл.



2015-11-24 12:25 GMT+03:00 TheGoblinHero <notifications@github.com>:

**Comment by TheGoblinHero** [comment]
Отправил

**Comment by alfredo-klaus** [comment]
Большая просьба добавить отображение партнерки OTTCLUB и отбражение зароботка за день в ней же. Спасибо.

**Comment by Starksoft** [comment]
Готово!
http://anybalance.ru/catalog.php?id=ab-sharing-ottclub
