### ISSUE TITLE
не работает ab-telephony-mgts

### ISSUE THREAD

**Issue by anyremote** [dukei/any-balance-providers#388]
по крайней мере в варианте когда указываются номер телефона и квартиры

"Неизвестная ошибка получения баланса, свяжитесь с разработчиком и проверьте номер телефона и номер квартиры"

22.12.15 была открыта заявка
http://support.anybalance.ru/tickets.php?id=5940

но похоже туда никто не смотрит (

**Comment by dukei** [comment]
Смотрят, просто очень много заявок. Но спасибо, что напомнили.

Попробуйте новую версию, пожалуйста:
http://anybalance.ru/catalog.php?id=ab-telephony-mgts&inapp=no

6 января 2016 г., 15:57 пользователь Mikhail Fedotov <
notifications@github.com> написал:
