### ISSUE TITLE
Добавление нового провайдера

### ISSUE THREAD

**Issue by xSilverSx** [dukei/any-balance-providers#484]
Пытаюсь добавить новый провайдер но никак не удается, или я делаю что то не так или не хватает прав, подскажите как это сделать?

**Comment by dukei** [comment]
Как именно вы пытаетесь добавить провайдер?

Если в исходный код, то вы можете это сделать с помощью pull request.

30 января 2016 г., 14:40 пользователь Владимир <notifications@github.com>
написал:

**Comment by xSilverSx** [comment]
Я пытался создать полностью новый, то есть добавить новые файлы, и как это сделать через сайт не нашел, а через приложение для виндоус при синхронизации выдает ошибку. 
Или лучше сюда скинуть файл? или ещё каким нибудь образом...?

**Comment by dukei** [comment]
Сначала вам надо форкнуть репозиторий на гитхабе
Склонировать его себе на локальный диск командой git clone
Добавить нового провайдера туда
Закомиттить изменения в свой форк git commit/git push
А потом на github уже создать пулреквест, предложить свои изменения в
внесению в основную ветку.
Вот эта статья может помочь: https://habrahabr.ru/post/125999/

1 февраля 2016 г., 12:52 пользователь Владимир <notifications@github.com>
написал:

**Comment by xSilverSx** [comment]
Все кажется разобрался, спасибо
