### ISSUE TITLE
Проблемы с paypal и яндекс маркетом

### ISSUE THREAD

**Issue by Lokinn** [dukei/any-balance-providers#635]
Пайпал ошибку выдает "ошибка получения данных с сайта api.paypal.com/что-то там дальше.

И проблема с яндекс маркет. Ищет только запросы состоящие из одного слова. Наверно пробелы не нравятся. Пробовал с кавычками, по аналогии с виндой, не помогло.

**Comment by dukei** [comment]
Добрый день!

Пришлите, пожалуйста, последний лог, обязательно с комментарием, что не
работает. Долгое нажатие на аккаунте и
выберите Показать последний лог. Затем меню Послать автору (или значок
Поделиться) и пошлите,
пожалуйста, по емейл.



19 февраля 2016 г., 10:16 пользователь Lokinn <notifications@github.com>
написал:

**Comment by Lokinn** [comment]
Я извиняюсь, но посмотрев лог, я там увидел зашифрованую информацию. Отправлять это, по понятным причинам, я не смогу.
Ошибка из лога выглядит так (если это важно):
19/02/2016 14:22:07 UpdaterService
onSetResult got result {"error":true,"message":"Ошибка получения данных с сайта http://api.paypal.com/v1/mwf/proxy-auth/token, GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)"}

С яндекс маркетом вроде ситуация разрешилась. Или я что то не правильно делал или яндекс что то поправил у себя. Пока работает.

**Comment by dukei** [comment]
Это значит, что у вас интернета нет на телефоне. Убедитесь, что сайты на
нем открываются, и попробуйте еще раз аккаунт обновить.
19 февр. 2016 г. 14:35 пользователь "Lokinn" <notifications@github.com>
написал:

**Comment by Lokinn** [comment]
Как так может быть? У меня шесть провайдеров. И только яндекс маркет и пайпал не работали. Сейчас вот и маркет заработал. Странно как то. Все программы использующие интернет работают (сейчас вот вам этот ответ пишу с телефона). На пайпале не забанен. Проверял.

**Comment by mousesport** [comment]
старая проблема, проверил - все работает. тему закрыл.
