### ISSUE TITLE
Давно не работает ab-internet-disconttelecom v3

### ISSUE THREAD

**Issue by ache** [dukei/any-balance-providers#664]
Ошибка получения данных с сайта https://lk.disconttelecom.ru/register/login/?return=/cabinet/?XXXXXXXXXXXXXXXXXXXXXXX
ProtocolException: Invalid redirect URI: /cabinet/?XXXXXXXXXXXXXXXXXXX

Android 6.0.1

**Comment by dukei** [comment]
Добрый день!

Пришлите, пожалуйста, последний лог, обязательно с комментарием, что не
работает. Долгое нажатие на аккаунте и
выберите Показать последний лог. Затем меню Послать автору (или значок
Поделиться) и пошлите,
пожалуйста, по емейл.



2016-02-24 20:18 GMT+03:00 Ache <notifications@github.com>:

**Comment by ache** [comment]
Починено в v4
