### ISSUE TITLE
Повторная покупка

### ISSUE THREAD

**Issue by Djuri-bachi** [dukei/any-balance-providers#847]
3 года назад купил программу для Samsung i9192, пользовался и все было отлично. 2 недели тому купил новый сартфон xiaomi redmi 3, соответсвенно повторно купил AnyBalance через PlayMarket. Но сегодня, после смены прошивки требует купить повторно. Как это исправить?

**Comment by Ign1000** [comment]
Здравствуйте.

Я не автор программы. Я только сопровождаю некоторые провадеры. Ищите
координаты автора и обращайтесь к нему. Сейчас дать адрес автора не могу, я
не дома.

30 лип. 2016 09:43 "Djuri-bachi" <notifications@github.com> пише:

3 года назад купил программу для Samsung i9192, пользовался и все было
отлично. 2 недели тому купил новый сартфон xiaomi redmi 3, соответсвенно
повторно купил AnyBalance через PlayMarket. Но сегодня, после смены
прошивки требует купить повторно. Как это исправить?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dukei/any-balance-providers/issues/847>, or mute the
thread

**Comment by dukei** [comment]
Сообщите, пожалуйста, ваш Гугл аккаунт, с которого покупали, и текущий
серийный номер лицензии из меню об AnyBalance. Восстановим лицензию.

30 июля 2016 г. 9:43 пользователь "Djuri-bachi" <notifications@github.com>
написал:

**Comment by Djuri-bachi** [comment]
andrashkojv@gmail.com
s/n 3BJJ9YG2YG2J26SG

**Comment by dukei** [comment]
Добрый день!

Лицензия восстановлена. Спасибо вам большое за поддержку!

2016-07-31 10:44 GMT+03:00 Djuri-bachi <notifications@github.com>:

**Comment by solarson** [comment]
Здравствуйте! У меня та же проблема — через несколько дней после покупки слетела лицензия. 
terzeman@gmail.com
M8N6ODLWIVOX

**Comment by dukei** [comment]
Проблема исправлена (была из-за двухсимочности телефона)

2016-08-18 16:11 GMT+03:00 solarson <notifications@github.com>:

**Comment by Zhenya111** [comment]
Здравствуйте.Совершил покупку в январе,точнее 19.01.2017 навсегда на одно устройство.Пару дней назад слетела лицензия.По какой причине-не знаю.Может,перепрошивка...Мой S/N:1K5KY39MBLV3D.

**Comment by Zhenya111** [comment]
google akkaunt:sashaptrv10@gmail.com

**Comment by dukei** [comment]
Лицензия исправлена, спасибо вам большое за поддержку!

2017-04-25 9:56 GMT+03:00 Zhenya111 <notifications@github.com>:

**Comment by Zhenya111** [comment]
Прошу прощения.Я не понимаю,что мне нужно сделать?Программу переустанавливал,кэш и т.д.очищал-всё равно пишет бесплатная,пожизненная.(((

**Comment by dukei** [comment]
Серийный номер именно тот, который Вы прислали? Не изменился он?

25 апр. 2017 г. 13:33 пользователь "Zhenya111" <notifications@github.com>
написал:

**Comment by Zhenya111** [comment]
серийный номер,который выдает программа:1К5KY39MBLV3D.

**Comment by dukei** [comment]
Всё, теперь должно быть все ок. Можете ввести любой код активации в меню
Покупка

25 апр. 2017 г. 13:41 пользователь "Zhenya111" <notifications@github.com>
написал:

серийный номер,который выдает программа:1К5KY39MBLV3D.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dukei/any-balance-providers/issues/847#issuecomment-296991303>,
or mute the thread

**Comment by Zhenya111** [comment]
Верю,спасибо.)

**Comment by Aftalik** [comment]
Слетела лицензия.
SN: 2IUWZSB2SKM36

Программу покупал 2 раза:

Номер заказа: 12999763169054705758.1336923688620299
Дата заказа: 23.10.2014 14:54:36 YEKT

Номер заказа: 1346192541684580
Дата заказа: 27.11.2012 1:30:07 YEKT

Как восстановить лицензию?

**Comment by dukei** [comment]
Добрый день!

Спасибо за поддержку!

У программы есть три вида лицензий - вечная с привязкой к устройству,
годовая с привязкой к гугл аккаунту и вечная с привязкой к гугл аккаунту.
Лицензии главным образом обеспечивают подписку на обновления
версий провайдеров и установку провайдеров из каталога.

Похоже, вы приобрели лицензию, привязанную к устройству, которая
по сути своей является временной (до смены аппарата). О привязке к
устройству в программе и на сайте (http://anybalance.ru/shop ) написано.

Вопрос о привязке задают часто, поэтому я даже поместил ответ на него
в теме, посвященной программе на 4pda.ru:

Q. Почему привязка к устройству? Очень не хочется программу каждый раз
при замене телефона покупать...

Программа бесплатна, её не нужно покупать. Она работает и получает
балансы независимо от того, полная у вас версия или нет. А вот платная
функциональность - это пользование каталогом и автоматическое
обновление версий провайдеров, то есть, те вещи, которые требуют от
меня _постоянных_ затрат и труда. Пользуясь программой, вы же хотите,
чтобы при изменении личного кабинета я тут же выпускал обновленную
версию провайдера, правильно? Хотя мне, может быть, тоже не хочется
это делать каждый раз...

Если смена устройства происходит слишком быстро (до 2х месяцев) - то я
переношу лицензию на новое устройство. Устройство с полной лицензией
имеет полные возможности программы и автоматические обновления
провайдеров в течение всей своей жизни. Перепрошивка, аппаратный сброс
лицензию сохраняет.

Если вы часто меняете устройства или у вас одновременно несколько
устройств, вам может быть удобно купить лицензию с привязкой к гугл
аккаунту. Она не зависит от устройств, важно только, чтобы они работали
под вашим гугл аккаунтом. Лицензия, привязанная к гугл аккаунту, может
быть годовой (с возможным автопродлением) или вечной (в этом случае
вам больше никогда не понадобится покупать лицензию на программу).

Надеюсь на ваше понимание


2017-05-04 12:34 GMT+03:00 Aftalik <notifications@github.com>:

**Comment by Aftalik** [comment]
лицензия у меня нормально работала, а слетела только сейчас.
Офигенная поддержка.

**Comment by dukei** [comment]
Так вы же сменили телефон только сейчас. Месяц на новом телефоне лицензия
работает в демо режиме, потом переходит в бесплатный режим. Видимо, поэтому
вы не сразу заметили.

12 мая 2017 г. 4:27 пользователь "Aftalik" <notifications@github.com>
написал:

**Comment by vlagor3** [comment]
Добрый день. 
после смены аппарата не могу найти код активации, помогите пожалуйста.
vlagor3@gmail.com
246WSQSWJ9Y1Z

**Comment by dukei** [comment]
Добрый день!

Спасибо за поддержку!

У программы есть три вида лицензий - вечная с привязкой к устройству,
годовая с привязкой к гугл аккаунту и вечная с привязкой к гугл аккаунту.
Лицензии главным образом обеспечивают подписку на обновления
версий провайдеров и установку провайдеров из каталога.

Похоже, вы приобрели лицензию, привязанную к устройству, которая
по сути своей является временной (до смены аппарата). О привязке к
устройству в программе и на сайте (http://anybalance.ru/shop ) написано.

Вопрос о привязке задают часто, поэтому я даже поместил ответ на него
в теме, посвященной программе на 4pda.ru:

Q. Почему привязка к устройству? Очень не хочется программу каждый раз
при замене телефона покупать...

Программа бесплатна, её не нужно покупать. Она работает и получает
балансы независимо от того, полная у вас версия или нет. А вот платная
функциональность - это пользование каталогом и автоматическое
обновление версий провайдеров, то есть, те вещи, которые требуют от
меня _постоянных_ затрат и труда. Пользуясь программой, вы же хотите,
чтобы при изменении личного кабинета я тут же выпускал обновленную
версию провайдера, правильно? Хотя мне, может быть, тоже не хочется
это делать каждый раз...

Если смена устройства происходит слишком быстро (до 2х месяцев) - то я
переношу лицензию на новое устройство. Устройство с полной лицензией
имеет полные возможности программы и автоматические обновления
провайдеров в течение всей своей жизни. Перепрошивка, аппаратный сброс
лицензию сохраняет.

Если вы часто меняете устройства или у вас одновременно несколько
устройств, вам может быть удобно купить лицензию с привязкой к гугл
аккаунту. Она не зависит от устройств, важно только, чтобы они работали
под вашим гугл аккаунтом. Лицензия, привязанная к гугл аккаунту, может
быть годовой (с возможным автопродлением) или вечной (в этом случае
вам больше никогда не понадобится покупать лицензию на программу).

Надеюсь на ваше понимание

22 мая 2017 г. 14:07 пользователь "vlagor3" <notifications@github.com>
написал:

**Comment by vlagor3** [comment]
ясно

22 мая 2017 г., 14:29 пользователь Dmitry Kochin <notifications@github.com>
написал:

**Comment by 775464** [comment]
Здравствуйте.
У меня тоже слетела лицензия:
775464@gmail.com
S/N: 21RNPPFOWGOP0

Почините, пожалуйста.

**Comment by dukei** [comment]
Исправлено.

Спасибо вам большое за поддержку!

2018-01-18 9:08 GMT+03:00 775464 <notifications@github.com>:

**Comment by Malgrat** [comment]
Здравствуйте!
Похоже у меня слетела лицензия ( проверьте плз 

malgratr@gmail.com 
3fu8wg8xbvqfa

**Comment by dukei** [comment]
Добрый день!

Спасибо за поддержку!

У программы есть три вида лицензий - вечная с привязкой к устройству,
годовая с привязкой к гугл аккаунту и вечная с привязкой к гугл аккаунту.
Лицензии главным образом обеспечивают подписку на обновления
версий провайдеров и установку провайдеров из каталога.

Вы приобрели лицензию, привязанную к устройству, которая
по сути своей является временной (до смены аппарата). О привязке к
устройству в программе и на сайте (http://anybalance.ru/shop ) написано.

Вопрос о привязке задают часто, поэтому я даже поместил ответ на него
в теме, посвященной программе на 4pda.ru:

Q. Почему привязка к устройству? Очень не хочется программу каждый раз
при замене телефона покупать...

Программа бесплатна, её не нужно покупать. Она работает и получает
балансы независимо от того, полная у вас версия или нет. А вот платная
функциональность - это пользование каталогом и автоматическое
обновление версий провайдеров, то есть, те вещи, которые требуют от
меня _постоянных_ затрат и труда. Пользуясь программой, вы же хотите,
чтобы при изменении личного кабинета я тут же выпускал обновленную
версию провайдера, правильно? Хотя мне, может быть, тоже не хочется
это делать каждый раз...

Если смена устройства происходит слишком быстро (до 2х месяцев) - то я
переношу лицензию на новое устройство. Устройство с полной лицензией
имеет полные возможности программы и автоматические обновления
провайдеров в течение всей своей жизни. Перепрошивка, аппаратный сброс
лицензию сохраняет.

Если вы часто меняете устройства или у вас одновременно несколько
устройств, вам может быть удобно купить лицензию с привязкой к гугл
аккаунту. Она не зависит от устройств, важно только, чтобы они работали
под вашим гугл аккаунтом. Лицензия, привязанная к гугл аккаунту, может
быть годовой (с возможным автопродлением) или вечной (в этом случае
вам больше никогда не понадобится покупать лицензию на программу).

Надеюсь на ваше понимание

пт, 5 окт. 2018 г. в 6:49, Malgrat <notifications@github.com>:

**Comment by pelentron** [comment]
Обновился на 9 Андроид и лицензия ушла.
pelentron@gmail.com
7xtfjufctn8 (вроде верно переписал)

**Comment by dukei** [comment]
Лицензия восстановлена, спасибо вам большое за поддержку!

ср, 16 янв. 2019 г. в 12:31, pelentron <notifications@github.com>:

**Comment by z48zzzzz** [comment]
Здравствуйте! Лицензия не устанавливается на другой телефон (заменил). S/N: 3CJNM8D2LATUC? гугл аккаунт zlobinvalipetsk@gmail.com

**Comment by yuriy71** [comment]
Здравствуйте,
Появилась та-же проблема, слетела лицензия.
Телефон не менял. Можете исправить?
yuriy71@gmail.com
214FF56093FF4886

**Comment by dukei** [comment]
Добрый день!

 Сообщите, пожалуйста, текущий серийный номер из меню Об AnyBalance.

Если там статус лицензии "Неверная", то программе не удалось соединиться с
сервером лицензирования. Чаще всего такое случается, когда программе
заблокирован доступ в интернет adGuard или подобной программой. Пожалуйста,
настройте там для AnyBalance исключения - необходим неограниченный доступ в
интернет. Тогда лицензия сразу появится.

Спасибо за поддержку!

чт, 10 окт. 2019 г. в 08:49, yuriy71 <notifications@github.com>:

**Comment by SerzhAntz** [comment]
Куплена лицензия на аккаунт Google. На новом устройстве пишет:
Лицензия на имя: null
Тип: Неверная
Истекает: Пожизненная
S/N: 2TLSJP8A4ZSIL

**Comment by dukei** [comment]
Добрый день!

Статус "Неверная" означает, что программе не удалось соединиться с сервером
лицензирования. Чаще всего такое случается, когда программе заблокирован
доступ в интернет adGuard или подобной программой. Пожалуйста, настройте
там для AnyBalance исключения - необходим неограниченный доступ в интернет.
Тогда лицензия сразу появится.

Спасибо за поддержку!

вс, 20 окт. 2019 г., 0:29 SerzhAntz <notifications@github.com>:

**Comment by SerzhAntz** [comment]
Да, спасибо. Именно AdGuard мешал.

**Comment by babar1905** [comment]
Добрый день !
Такая же история - перепрошил устройство (Android 10)/ Слетела лицензия. Покупал  02.11.2019
Счет № | 99132809 (выписан 02.11.2019 23:28:56)
SN сейчас: 3LQ3T4KBAZZBD

**Comment by dukei** [comment]
Лицензия восстановлена. Спасибо вам большое за поддержку!

ср, 12 февр. 2020 г. в 17:10, babar1905 <notifications@github.com>:

**Comment by vladislavik58** [comment]
У меня та же самая проблема что и остальных, слетела лицензия. Устройство не менял, прошивку не менял. Пишет бесплатная, пожизненная. Почините пожалуйста. Sn 1Y42VRGGVGGDG
