### ISSUE TITLE
Перестали работать газпром и авито

### ISSUE THREAD

**Issue by Vitlo** [dukei/any-balance-providers#914]
Газпром в Ростове-на-Дону переехал с ростоврегионгаз на газ.смородина.онлайн, плагин работать перестал.
И авито ростовский не хочет работать. Выдает ошибку что название города может содержать только цифры и буквы. А как я, по мнению разработчика плагина, могу написать город rostov-na-donu без дефисов?

**Comment by dukei** [comment]
По газпрому пришлите последний лог, пожалуйста.

14 февр. 2017 г. 8:59 пользователь "Vitlo" <notifications@github.com>
написал:
