### ISSUE TITLE
Не работает провайдер Netbynet 2.0.30

### ISSUE THREAD

**Issue by k03mad** [dukei/any-balance-providers#918]
Привет, провайдер перестал обновляться 9 марта.

30 минут назад провайдер обновился до 30 версии - подумал, что поддержали новый кабинет, но теперь приходит ошибка парсинга json.

В логе:

```
20/03/2017 20:45:09 UpdaterService
onSetResult got result {"message":"Сервер вернул ошибочные данные: Unexpected token A in JSON at position 0","error":true}
```

В новый ЛК на my.netbynet.ru с того же устройства из браузера заходит.

**Comment by dukei** [comment]
Добрый день!

Пришлите, пожалуйста, последний лог, обязательно с комментарием, что не
работает. Долгое нажатие на аккаунте и
выберите Показать последний лог. Затем меню Послать автору (или значок
Поделиться) и пошлите,
пожалуйста, по емейл.



20 марта 2017 г., 20:51 пользователь Kirill Molchanov <
notifications@github.com> написал:

**Comment by k03mad** [comment]
Починили в 2.0.31, спасибо!
