### ISSUE TITLE
Не работает с Android 8 (Android O Developer preview 2)

### ISSUE THREAD

**Issue by reykjavi** [dukei/any-balance-providers#925]
Здравствуйте.
Понимаю, что бегу впереди паровоза :)
Но тем не менее, обнаружил, что инструмент, которому я доверяю, не работает с новой версией Андроида: все провайдеры падают с ошибкой IllegalArgumentException: cipherSuite SSL_RSA_WITH_RC4_128_MD5 is not supported.
Не надеюсь на быстрое разрешение, но, тем не менее, имейте в виду на будущее.

Спасибо!

**Comment by dukei** [comment]
А это на каком провайдере?

20 мая 2017 г. 19:27 пользователь "reykjavi" <notifications@github.com>
написал:

**Comment by reykjavi** [comment]
На всех, что есть: MTS, Tele2, Onlime.

**Comment by reykjavi** [comment]
Я очень рад, что вышла обновленная версия, которая работает под Android 8.
Огромное спасибо, Дмитрий.
