### ISSUE TITLE
Не подключается library.js

### ISSUE THREAD

**Issue by KozakIvan** [dukei/any-balance-providers#931]
При тестировании провайдера на смартфоне под андройд 6 (AnyBalance+) не видит функции из library.js (checkEmpty is not defined, что с префиксом AB, что без него), хотя в манифесте она подключена в секции depends. В чём может быть дело ?

**Comment by KozakIvan** [comment]
Я так понимаю при сборке провайдера он автоматически добавляется в манифест

**Comment by dukei** [comment]
Да, именно так. Сборку можно произвести и вручную (только Windows), для этого предназначен файл packsend.bat, помещенный в каталог с провайдером (должны быть установлены переменные окружения ABROOT - путь к локальному гит репозиторию провайдеров и ABREPOS в формате repo*path;repo*path - пути к модулям). 
packsend.bat можно взять отсюда: https://github.com/dukei/any-balance-providers/tree/master/extra/development/ab-stark-typical-provider

В простом случае должно быть что-то вроде
ABROOT=C:/any-balance-providers
ABREPOS=%ABROOT%/modules
