### ISSUE TITLE
Слетела лицензия

### ISSUE THREAD

**Issue by k-slava** [dukei/any-balance-providers#947]
Здравствуйте! Слетела лицензия на новом аппарате.
Аккаунт, с которого покупал kuznetsoff.vs@gmail.com текущий SN 2418IYJ97I17Y

**Comment by dukei** [comment]
Добрый день!

Спасибо за поддержку!

У программы есть три вида лицензий - вечная с привязкой к устройству,
годовая с привязкой к гугл аккаунту и вечная с привязкой к гугл аккаунту.
Лицензии главным образом обеспечивают подписку на обновления
версий провайдеров и установку провайдеров из каталога.

Похоже, вы приобрели лицензию, привязанную к устройству, которая
по сути своей является временной (до смены аппарата). О привязке к
устройству в программе и на сайте (http://anybalance.ru/shop ) написано.

Вопрос о привязке задают часто, поэтому я даже поместил ответ на него
в теме, посвященной программе на 4pda.ru:

Q. Почему привязка к устройству? Очень не хочется программу каждый раз
при замене телефона покупать...

Программа бесплатна, её не нужно покупать. Она работает и получает
балансы независимо от того, полная у вас версия или нет. А вот платная
функциональность - это пользование каталогом и автоматическое
обновление версий провайдеров, то есть, те вещи, которые требуют от
меня _постоянных_ затрат и труда. Пользуясь программой, вы же хотите,
чтобы при изменении личного кабинета я тут же выпускал обновленную
версию провайдера, правильно? Хотя мне, может быть, тоже не хочется
это делать каждый раз...

Если смена устройства происходит слишком быстро (до 2х месяцев) - то я
переношу лицензию на новое устройство. Устройство с полной лицензией
имеет полные возможности программы и автоматические обновления
провайдеров в течение всей своей жизни. Перепрошивка, аппаратный сброс
лицензию сохраняет.

Если вы часто меняете устройства или у вас одновременно несколько
устройств, вам может быть удобно купить лицензию с привязкой к гугл
аккаунту. Она не зависит от устройств, важно только, чтобы они работали
под вашим гугл аккаунтом. Лицензия, привязанная к гугл аккаунту, может
быть годовой (с возможным автопродлением) или вечной (в этом случае
вам больше никогда не понадобится покупать лицензию на программу).

Надеюсь на ваше понимание

**Comment by k-slava** [comment]
Я тоже надеюсь на Ваше понимание.
Я покупал программу, когда была 1 Pro лицензия. В остальных программах разработчики не ухудшают функциональность купленного приложения, думают о пользователях, когда внедряют новые правила лицензирования. Я никогда не покупаю лицензию в привязке к устройству.
Аналогичная история у меня была с Progorod - так там никто не урезал мою лицензию, все восстановили. 
--
With regards,
Vyacheslav Kuznetsov
Sent from my mobile device Monday, 25 September 2017, 00:17PM +03:00 from Dmitry Kochin  notifications@github.com :

>Добрый день!
>
>Спасибо за поддержку!
>
>У программы есть три вида лицензий - вечная с привязкой к устройству,
>годовая с привязкой к гугл аккаунту и вечная с привязкой к гугл аккаунту.
>Лицензии главным образом обеспечивают подписку на обновления
>версий провайдеров и установку провайдеров из каталога.
>
>Похоже, вы приобрели лицензию, привязанную к устройству, которая
>по сути своей является временной (до смены аппарата). О привязке к
>устройству в программе и на сайте ( http://anybalance.ru/shop ) написано.
>
>Вопрос о привязке задают часто, поэтому я даже поместил ответ на него
>в теме, посвященной программе на 4pda.ru:
>
>Q. Почему привязка к устройству? Очень не хочется программу каждый раз
>при замене телефона покупать...
>
>Программа бесплатна, её не нужно покупать. Она работает и получает
>балансы независимо от того, полная у вас версия или нет. А вот платная
>функциональность - это пользование каталогом и автоматическое
>обновление версий провайдеров, то есть, те вещи, которые требуют от
>меня _постоянных_ затрат и труда. Пользуясь программой, вы же хотите,
>чтобы при изменении личного кабинета я тут же выпускал обновленную
>версию провайдера, правильно? Хотя мне, может быть, тоже не хочется
>это делать каждый раз...
>
>Если смена устройства происходит слишком быстро (до 2х месяцев) - то я
>переношу лицензию на новое устройство. Устройство с полной лицензией
>имеет полные возможности программы и автоматические обновления
>провайдеров в течение всей своей жизни. Перепрошивка, аппаратный сброс
>лицензию сохраняет.
>
>Если вы часто меняете устройства или у вас одновременно несколько
>устройств, вам может быть удобно купить лицензию с привязкой к гугл
>аккаунту. Она не зависит от устройств, важно только, чтобы они работали
>под вашим гугл аккаунтом. Лицензия, привязанная к гугл аккаунту, может
>быть годовой (с возможным автопродлением) или вечной (в этом случае
>вам больше никогда не понадобится покупать лицензию на программу).
>
>Надеюсь на ваше понимание
>

**Comment by dukei** [comment]
К сожалению, этот тип лицензии не предусматривает перенос на другое
устройство. Для этого нужно приобрести лицензию с привязкой к гугл аккаунту.

Но вы можете продолжать пользоваться лицензией на прошлом телефоне без
ограничений.

Пояснения, почему так, я уже написал в прошлом письме. Программа
представляет сервис. Сервис подразумевает постоянную работу (над
обновлением провайдеров), поэтому оплачивается периодически. Если вы хотите
вечную лицензию с привязкой к гугл аккаунту — её тоже можно купить, но
стоит она дороже. Дешёвая лицензия — с привязкой к устройству. Выбрать тип
лицензии можно в меню Покупка.

В качестве альтернативы — можете пользоваться программой бесплатно,
устанавливая провайдеры вручную.

P.S. Вы когда устройство поменяли, платили за новое? Или вам засчитали
платеж за старое?

**Comment by k-slava** [comment]
Отвратительное отношение к клиенту.
Когда я покупал лицензию, привязки к одному устройству не было.
--
With regards,
Vyacheslav Kuznetsov
Sent from my mobile device Monday, 25 September 2017, 00:40PM +03:00 from Dmitry Kochin  notifications@github.com :

>К сожалению, этот тип лицензии не предусматривает перенос на другое
>устройство. Для этого нужно приобрести лицензию с привязкой к гугл аккаунту.
>
>Но вы можете продолжать пользоваться лицензией на прошлом телефоне без
>ограничений.
>
>Пояснения, почему так, я уже написал в прошлом письме. Программа
>представляет сервис. Сервис подразумевает постоянную работу (над
>обновлением провайдеров), поэтому оплачивается периодически. Если вы хотите
>вечную лицензию с привязкой к гугл аккаунту — её тоже можно купить, но
>стоит она дороже. Дешёвая лицензия — с привязкой к устройству. Выбрать тип
>лицензии можно в меню Покупка.
>
>В качестве альтернативы — можете пользоваться программой бесплатно,
>устанавливая провайдеры вручную.
>
>P.S. Вы когда устройство поменяли, платили за новое? Или вам засчитали
>платеж за старое?
>
>
>

**Comment by dukei** [comment]
Ну что вы.

Привязка к одному устройству была изначально. Если вы покупали через гугл
плей, то лицензия даже называется License per device, что означает На
устройство. Можете это проверить к себя на wallet.google.com

Просто впоследствии появились лицензии с привязкой к гугл аккаунту по
просьбам пользователей.

В любом случае, учитывая, что вы 4 года пользовались лицензией на
устройство, этот вид лицензии для вас наиболее выгоден.

**Comment by k-slava** [comment]
Так без проблем. На том устройстве удалить? Тогда заработает?
--
With regards,
Vyacheslav Kuznetsov
Sent from my mobile device Monday, 25 September 2017, 01:20PM +03:00 from Dmitry Kochin  notifications@github.com :

>Ну что вы.
>
>Привязка к одному устройству была изначально. Если вы покупали через гугл
>плей, то лицензия даже называется License per device, что означает На
>устройство. Можете это проверить к себя на wallet.google.com
>
>Просто впоследствии появились лицензии с привязкой к гугл аккаунту по
>просьбам пользователей.
>
>В любом случае, учитывая, что вы 4 года пользовались лицензией на
>устройство, этот вид лицензии для вас наиболее выгоден.
>

**Comment by dukei** [comment]
Нет, на том устройстве пользоваться.
