### ISSUE TITLE
fenix web servers?

### ISSUE THREAD

**Issue by mousesport** [dukei/any-balance-providers#954]
Подскажите зачем в any дебагер нужен fenix web server?
установил его
но получаю вывод:
AnyBalanceDebugger: ERROR: anybalance-manifest.xml can not be loaded!
AnyBalanceDebugger: WARNING: Some dependencies were not loaded (:). Check network tab for details.

**Comment by dukei** [comment]
Он нужен как раз для загрузки файлов с файловой системы, потому что сам
браузер туда доступа не имеет. Возможно, какая-то ошибка в манифесте. Надо
консоль открыт и посмотреть, что именно случилось.

**Comment by mousesport** [comment]
так и не понял, зачем он нужен... (напоминает файловый менеджер только через веб )
ошибку выдает т.к  ищет манифест файл в корне на диске С (ему туда подпихнуть манифест провайдера? ) - из любопытства подпихивал и ничего не нового не произошло...
вроде бы раньше в файле -anybalance.html просто указывал путь до файлов и усе.....
<script>
        var g_api_preferences = {
		  contract: '',
		  password: ''
        };
  </script>
<script src="D:\SVNanybalance\trunk\providers\ab-adv-admitad\main.js"></script>
<script src="D:\SVNanybalance\trunk\providers\ab-adv-admitad\library.js"></script>

Paths to local module repositories это путь до D:\SVNanybalance\trunk\modules
непонятно.......

**Comment by mousesport** [comment]
разобрался, вещь удобная... (в any дебегере подключать библиотеки не требуется).
главное в настройках дебагера указать путь до папки локального репозитория .....\trunk\modules
