### ISSUE TITLE
recapcha debugger

### ISSUE THREAD

**Issue by mousesport** [dukei/any-balance-providers#957]
Дим, подскажи:
 запускаю recapcha debugger, fenix, кидаю в хром файл _anydebugger првайдера получаю recapcha, подтверждаю её, но она не передается обратно в anydebugger, тупо отбратный отчет отсчитал и усе.... (Время проверки истекло. Установите флажок и повторите попытку.)
в чем может быть дело?
![2017-11-02_21-59-58](https://user-images.githubusercontent.com/15033650/32344879-5c16eb16-c019-11e7-9063-80ff8e02154e.png)

**Comment by dukei** [comment]
Хм, у меня такое тоже несколько раз было. Перезапуск помогал. Есть там
какой-то баг, видимо, но я его пока не поймал.

**Comment by dukei** [comment]
Исправлено, можно скачать новую версию с http://anybalance.ru/download/anybalance-recaptcha.jar
Теперь работает четко. Проблема была из-за гарбадж коллектора.
