### ISSUE TITLE
HMAC-SHA256

### ISSUE THREAD

**Issue by mousesport** [dukei/any-balance-providers#998]
@dukei - Дим т.к ты JS-Отец не мог бы подсказать по шифрованию, т.к сам никогда до этого не сталкивался...
не могу разобраться с формированием подписи signature, читаю документацию, вроде бы все понятно:
> 
> Signature
> 
> Signature is a HMAC-SHA256 encoded message containing: nonce, client ID and API key. The HMAC-SHA256 code must be generated using a secret key that was generated with your API key. This code must be converted to it's hexadecimal representation (64 uppercase characters).
> 
> Note: Please specify the SSL version as TLSv1.2
> 
> Example (Python):
> 
> message = userid + api_key + nonce
> signature = hmac.new(API_SECRET, msg=message, digestmod=hashlib.sha256).hexdigest().upper()
> 
> Example (Java):
> 
> public static String apiSignature(String userId, String key, String nonce, String secret) throws Exception {
>     String data = userId+key+nonce;
>     Mac hmacSha256 = Mac.getInstance("HmacSHA256");
>     SecretKeySpec secretKey = new SecretKeySpec(secret.getBytes(), "HmacSHA256");
>     hmacSha256.init(secretKey);
>     return Hex.encodeHexString(hmacSha256.doFinal(data.getBytes())).toUpperCase();
> }
> 
> public static boolean checkApiSignature(String userId, String key, String nonce, String secret, String signature) throws Exception {
>     String data = userId+key+nonce;
>     Mac hmacSha256 = Mac.getInstance("HmacSHA256");
>     SecretKeySpec secretKey = new SecretKeySpec(secret.getBytes(), "HmacSHA256");
>     hmacSha256.init(secretKey);
>     String signatrueTmp = Hex.encodeHexString(hmacSha256.doFinal(data.getBytes())).toUpperCase();
>     if(signature.equals(signatrueTmp)) {
>         return true;
>     }
>     return false;
> }

в манифест подключил модули:
`	<depends>
		<module id="library"/>
		<module id="crypt/cryptojs/hmac"/>
   		<module id="crypt/cryptojs/sha256"/>
   		<module id="crypt/cryptojs/base64"/>
	</depends>`

вроде бы и изобразил код:
```
	var nonce = new Date().getTime();
	var str = nonce + prefs.worker + prefs.api;
	var hash = CryptoJS.HmacSHA256(str,prefs.secret).toString();
	var signature = hash.toString(CryptoJS.enc.Base64);

	AnyBalance.trace('nonce:' + nonce);
	AnyBalance.trace('api:' + prefs.api);
	AnyBalance.trace('secret_api:' + prefs.secret);
	AnyBalance.trace('worker:' + prefs.worker);
	AnyBalance.trace('coin:' + prefs.coin);
	AnyBalance.trace('signature:' + signature);

	var baseurl = 'https://antpool.com/';
	
	var html = AnyBalance.requestPost(baseurl + 'api/poolStats.htm?key=' + prefs.api + '&nonce=' + nonce + '&signature=' + signature + '&coin=' + prefs.coin, g_headers);
	if (!html || AnyBalance.getLastStatusCode() > 400) {
		AnyBalance.trace(html);
		throw new AnyBalance.Error('Ошибка при подключении к сайту! Возможно сайт изменился .');
	}
	AnyBalance.trace(html);
	var result = { success: true };
```

Ответ получаю следующий:
trace: {"code":-7,"message":"Signature error"}

В чем ошибка понять не могу... (вроде бы все, как мануале)

**Comment by dukei** [comment]
В доке написано:
This code must be converted to it's hexadecimal representation (64 uppercase characters).

А ты конвертируешь её в Base64. А надо в Hex.

hash.toString().toUpperCase();

**Comment by mousesport** [comment]
видимо здесь, что-то еще, ответ получаю тот же.
нет еще мыслей?

**Comment by dukei** [comment]
Значит, подпись генерируется неправильно.
Надо добиться, чтобы подпись генерировалась одинаково при одних и тех же входных параметрах здесь: https://www.ideone.com/ieGjoj и в javascript в твоём коде. Как подпись совпадет, всё заработает.

**Comment by mousesport** [comment]
@dukei спасибо тебе, разобрался
